3 haku
otavanopisto/client-opinvoimala-frontend pull request #7
Opened 2024-02-05 10:45 UTC by avukkonen

Ei issueta frontille.

2024-02-09 08:20 UTC, TeroOtavia approved these changes, later dismissed

2024-02-09 08:22 UTC, TeroOtavia reviewed
Hats off from package.json

2024-02-09 08:25 UTC, TeroOtavia requested changes

2024-02-09 08:25 UTC, TeroOtavia commented on package.json
>    },
Hats off!

2024-02-26 10:57 UTC, TeroOtavia submitted a review, later dismissed

2024-03-07 09:48 UTC, jjlankinen approved these changes

2024-03-07 09:50 UTC, merged